/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Gishere (https://sketchfab.com/Gishere)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/88ed1d3228c14c01ab5078c960d01228
Title: 银耳相思鸟
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import * as THREE from 'three';
import { AnimationUtils } from 'three';

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/assets/models/bird/scene.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const fixedAnimations = React.useMemo(() => {
    return animations.map((clip) => {
      const converted = AnimationUtils.subclip(clip, clip.name, 0, clip.duration * 30);
      converted.loop = THREE.LoopRepeat;
      converted.repetitions = Infinity;
      return converted;
    });
  }, [animations]);
  const { actions } = useAnimations(fixedAnimations, group);

  useEffect(() => {
    const action = actions['Unreal Take'];
    if (!action) return;

    action.reset();
    action.setLoop(THREE.LoopRepeat, Infinity);
    action.clampWhenFinished = false;
    action.enabled = true;
    action.play();

    return () => action.stop();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[1.566, 0, 0]} scale={13.5}>
          <group name="niaofbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Mesh_RobinLowPoly" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Mat_Robin}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Mat_RobinFeathewr}
                    skeleton={nodes.Object_8.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/bird/scene.gltf');
export default Model;
